import { QueryResponse } from './reportExporter';

export function exportWordDocxReport(question: string, result: QueryResponse) {
  const timestamp = new Date().toLocaleString('en-US', {
    dateStyle: 'full',
    timeStyle: 'medium',
  });

  const citationsText = result.citations.length === 0 
    ? 'No formal source citations referenced.'
    : result.citations.map((c, i) => `${i + 1}. [${c.source}] Chunk: ${c.chunk_id} (${c.source === 'duckduckgo_web_search' ? 'External Web Fallback' : 'Internal GraphRAG'})`).join('\n');

  const attemptsText = result.attempts_log.length === 0
    ? ''
    : '\n\n3. SELF-CORRECTION & REWRITE AUDIT TRAIL\n' + result.attempts_log.map(log => 
        `• Attempt #${log.retry_index + 1} (Confidence: ${log.confidence}%)\n  Query: "${log.query_used}"\n  Reasoning: ${log.reasoning}`
      ).join('\n\n');

  const docxContent = `
PROJECT CHRONOS EXECUTIVE BRIEFING REPORT
--------------------------------------------------------------------------------
Generated: ${timestamp}
System Confidence: ${result.confidence_score}%
Grounding Status: ${result.is_valid ? 'Validated & Grounded' : 'Low-Grounding Warning'}
Self-Correction Retries: ${result.retries}

QUERY ANALYZED:
"${question}"

--------------------------------------------------------------------------------
1. EXECUTIVE SYNTHESIZED FINDINGS

${result.answer}

--------------------------------------------------------------------------------
2. SOURCES & CITATIONS AUDIT

${citationsText}
${attemptsText}

--------------------------------------------------------------------------------
Confidential Enterprise Report • Generated by Project Chronos GraphRAG Engine
`;

  const blob = new Blob([docxContent], { type: 'application/msword;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');

  const sanitizedTitle = (question || 'report')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '_')
    .slice(0, 35);

  link.href = url;
  link.setAttribute('download', `Chronos_Report_${sanitizedTitle}.docx`);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
